version: '3.9'

services:

  laravel_app:
    image: oleksiivelychko/php8fpm
    build:
      context: ./docker/php
      dockerfile: php8fpm.dockerfile
    depends_on:
      - laravel_db
    volumes:
      - .:/var/www
    tty: true

  laravel_web:
    image: nginx
    restart: always
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    depends_on:
      - laravel_app
    secrets:
      - source: server.crt
        target: /run/secrets/server.crt
      - source: server.key
        target: /run/secrets/server.key

  laravel_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
    ports:
      - ${DB_PORT:-3306}:3306

  laravel_memory:
    restart: always
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - ${REDIS_PORT:-6379}:6379

  laravel_queue:
    restart: always
    image: oleksiivelychko/php8fpm
    depends_on:
      - laravel_app
    command: php artisan queue:work --sleep=5 --tries=5
    volumes:
      - .:/var/www

